[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  sandeepmistry/LoRa@^0.8.0
  mikalhart/TinyGPSPlus@^1.1.0
  https://github.com/adafruit/Adafruit_ADXL375.git
  adafruit/Adafruit SSD1306@^2.5.13
  adafruit/Adafruit GFX Library@^1.11.11
  adafruit/Adafruit BusIO
  adafruit/Adafruit Unified Sensor
